name: Update AoC Badges

on:
  schedule:
    - cron: '50 * 1-25 12 *'
  workflow_dispatch:
  push:

jobs:
  update-readme-badges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: joblo2213/aoc-badges-action@v3
        with:
          userid: 1034234
          session: ${{ secrets.aoc }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update badges
          file_pattern: README.md